import Head from 'next/head'
import Image from 'next/image'

export default function Home () {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>

      <main className=''>
        <h1 className=''>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className=''>
          Get started by editing{' '}
          <code className=''>pages/index.js</code>
        </p>

        <div className=''>
          <a className='' href='https://nextjs.org/docs'>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a className='' href='https://nextjs.org/learn'>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            className=''
            href='https://github.com/vercel/next.js/tree/canary/examples'
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            className=''
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className=''>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          rel='noopener noreferrer'
          target='_blank'
        >
          Powered by{' '}
          <span className=''>
            <Image
              alt='Vercel Logo'
              height={16}
              src='/vercel.svg'
              width={72}
            />
          </span>
        </a>
      </footer>
    </div>
  )
}
